<?php

namespace ContainerMnhjqj3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventSerializerService extends Mailer_KernelDevDebugContainer
{
    /**
     * Gets the private 'Mailer\Serializer\Messenger\EventSerializer' shared autowired service.
     *
     * @return \Mailer\Serializer\Messenger\EventSerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/Serializer.php';
        include_once \dirname(__DIR__, 4).'/src/Serializer/Messenger/EventSerializer.php';

        return $container->privates['Mailer\\Serializer\\Messenger\\EventSerializer'] = new \Mailer\Serializer\Messenger\EventSerializer(($container->services['serializer'] ?? $container->load('getSerializerService')));
    }
}
