<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnhjqj3\Mailer_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnhjqj3/Mailer_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnhjqj3.legacy');

    return;
}

if (!\class_exists(Mailer_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMnhjqj3\Mailer_KernelDevDebugContainer::class, Mailer_KernelDevDebugContainer::class, false);
}

return new \ContainerMnhjqj3\Mailer_KernelDevDebugContainer([
    'container.build_hash' => 'Mnhjqj3',
    'container.build_id' => 'f610d5a8',
    'container.build_time' => 1598441170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnhjqj3');
